name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend requirements (skip heavy ML deps)
        run: |
          python -m pip install --upgrade pip
          # Install core backend deps only to keep CI fast; transformers/torch are optional
          pip install Flask==3.0.0 flask-cors==4.0.0 SQLAlchemy==2.0.19 requests==2.31.0 youtube-transcript-api==0.6.2 python-dotenv==1.0.0
          pip install -r backend/dev-requirements.txt
      - name: Initialize DB
        run: |
          python backend/db_init.py
      - name: Run tests
        env:
          API_BASE_URL: "https://huggingface.co/spaces/Apoorv048/ai-active-learning-platform"
          # Optional: wait up to 10s for the Space to become responsive
          API_HEALTH_RETRY_SECONDS: "10"
        run: |
          python -m pytest -q
